add_newline = false

[aws]
disabled = true

[cmd_duration]
format = 'in [$duration]($style)'
style = '#abaebe'

[docker_context]
symbol = '🟣 '
style = '#764CC3 bold'

[nodejs]
symbol = '🕸  '

[python]
python_binary = ["python3", "python", "python2"]

[swift]
symbol = '􀫊  '
